name: cgsul2
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=1.11.0
  - numpy
  - blosc
  - pip
  - pip:
    - gym==0.21.0
    - flamingo-pytorch==0.0.17
    - einops==0.4.1
    - einops-exts==0.0.3
    - transformers==4.19.4
    - vit-pytorch==0.35.2
    - jupyterlab
    - tensorboardX
